### ISSUE TITLE
console warning: undefined symbol: _udev_device_get_action

### ISSUE THREAD

**Issue by DjThunder** [electronstudio/sdl2gdx#28]
When running a program with the library under linux (Debian10 and other), I have the following message:
```
EXTRACTED LOC /tmp/13024741725922545191.tmp
NATIVE METHOD: loading from  "/tmp/13024741725922545191.tmp"
             result 74  Failed loading udev_device_get_action: /tmp/jnigen/375939362/libsdl2gdx64.so: undefined symbol: _udev_device_get_action
```

I suppose it is the same cause: https://github.com/williamahartman/Jamepad/issues/33
I still not really understand if the udev functions are truly missing, or simply a dynamic linking failure (maybe better with static linking ?)

Anything I can do to help ?

Edit: I know it is better so ship libusb.dll on windows (and it is working for me), so perhaps it is the same with Linux ?
But even with the warning, gamepad is working (at least mine).

**Comment by electronstudio** [comment]
If it's working and is just a warning I wouldn't worry about it too much.  I would guess it's something SDL was compiled to use but only if it's available in that case.

Could you try:

    sudo apt install libudev0 libudev1 libudev-dev

and see if that fixes it?

Googling this message shows a couple of bug reports from SDL users, but neither of them has any solution.

The solution is probably just to recompile sdl2gdx.

I don't have time right now, and even if I did, I can't do a new release because JFrog Bintray has closed down!

**Comment by DjThunder** [comment]
It does not change anything.
Ok thanks !
